### ISSUE TITLE
Update the data_table yaml format

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1521]
**Is your feature request related to a problem? Please describe.**
The format of the data_table yaml will be updated to improve clarity and flexibility.
```
data_table:
- grid_name: ICE
  fieldname_in_model: sic_obs
  override_file:
  - file_name: INPUT/[hadisst_ice.data.nc](http://hadisst_ice.data.nc/)
    fieldname_in_file: ice
    interp_method: blinear
    multi_file:
    - next_file_name:
      prev_file_name:
    external_weights:
    - file_name: filename
      source: esmf
  factor: 0.01
  subregion:
  - type: "inside_region" #"outside_region"
    lon_start: 10
    lon_end: 11
    lat_start: 12
    lon_end: 13
``` 

**Describe the solution you'd like**
- [ ] the converter should be updated to convert the data table to this new format @uramirez8707 
- [ ] The code that reads in the data_table yaml format needs to be updated @abrooks1085 
- [ ] A schema needs to be added to check that a data table yaml format is valid https://github.com/NOAA-GFDL/FMS/pull/1515 @J-Lentz 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
