### ISSUE TITLE
Modern diag_manger: Crashes if freq is 0 days and you have static fields

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1524]
**Describe the bug**
If you have static fields in a file with a freq of 0 days. The code crashes with errors like:
```
49: FATAL from PE    49: Send data has not been called at the same time steps for the fields:ps_ic and ps in file:atmos_daily
```
where `pc_ic` is a static fields (initial pressure) 

**To Reproduce**
Have a file with static fields and non-static fields and a freq of 0 days.
```
title: C192.64bit
base_date: 0 0 0 0 0 0
diag_files:
- file_name: atmos_daily
  time_units: days
  unlimdim: time
  freq: 0 hours
  varlist:
  - module: dynamics
    var_name: ps_ic
    reduction: none
    kind: r4
  - module: dynamics
    var_name: ps
    reduction: none
    kind: r4
```
**Expected behavior**
Having static fields should be allowed in files with a freq of 0 days.

The errors comes from: https://github.com/NOAA-GFDL/FMS/blob/42f8506512e1b5b43982320f5b9d4ca1ca9cbebd/diag_manager/fms_diag_file_object.F90#L1847-L1851
The checks should not happen if the field is static. 

**System Environment**
This happens in any system. 

**Additional context**
N/A
