### ISSUE TITLE
parser hangs if using an invalid yaml

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1562]
**Describe the bug**
If you have an invalid yaml such as
```
title:c384L49_esm5PIcontrol
baseDate: 1960 1 1 1 1 1 1
diag_files:
-    fileName: "atmos_daily"
     freq: 24
     frequnit: hours
     timeunit: days
     unlimdim: time
```
The parser hangs when trying to parse the file.

**To Reproduce**
Modify any of the parser unit tests to use an invalid yaml and you will see that the code hangs

**Expected behavior**
The parser should not hang, instead it should produce an error message

This can be done by checking the output to [yaml_parser_scan](https://github.com/NOAA-GFDL/FMS/blob/361352e0b410373ba259259627f4b714b15cff57/parser/yaml_parser_binding.c#L344). It will be 0 on error. 

**System Environment**
This happens in any system

**Additional context**
Thanks @uwagura for bringing this up
