### ISSUE TITLE
Modern diag_manager :: new_file_freq, start_time, and file_duration keys

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1594]
**Describe the bug**
The following test cases are not working correctly:
```yaml
title: test_diag_manager_01
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_multi_file%4yr%2mo%2dy%2hr
  time_units: days
  unlimdim: time
  freq: 1 hours
  new_file_freq: 6 hours
  module: atmos
  reduction: average
  kind: r4
  varlist:
  - var_name: ua
```
Here I expected a new file to be created every six hours (i.e test_multi_file_0002_01_01_06.nc, test_multi_file_0002_01_01_12.nc, etc), but instead I just get one file.

```yaml
title: test_diag_manager_01
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_multi_file
  time_units: days
  unlimdim: time
  freq: 2 hours
  start_time: 2 1 1 12 0 0
  file_duration: 8 hours
  module: atmos
  reduction: average
  kind: r4
  varlist:
  - var_name: ua
```

Here I expected the file, test_multi_file.nc, to start writing output at 2 1 1 12 0 0 for 8 hours, but instead it starts at the beginning of the simulation and continues til the end. 

**To Reproduce**
Run the unit tests with the example diag_table.yamls above

**Expected behavior**
Those test cases should be working as advertised

**System Environment**
This happens in any system

**Additional context**
N/A
