### ISSUE TITLE
MODERN DIAG MANAGER: Potential to improve the diag_table yaml format further using anchors

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1677]
**Is your feature request related to a problem? Please describe.**
There may be some cases where multiple variables are needed to be outputted at different frequencies (i.e daily, monthly)

With the current yaml format, this will require duplicating a lot of info and required updating multiple places

For example, 
```yaml
title: test_none
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_4xdaily
  freq: 6 hours
  time_units: hours
  unlimdim: time
  module: ocn_mod
  reduction: none
  kind: r4
  varlist:
  - var_name: var0
  - var_name: var1
  - var_name: var2
  - var_name: var3
  - var_name: var4
  - var_name: var3
    output_name: var3_Z
    zbounds: 2. 3.
- file_name: test_daily
  freq: 1 days
  time_units: hours
  unlimdim: time
  module: ocn_mod
  reduction: none
  kind: r4
  varlist:
  - var_name: var0
  - var_name: var1
  - var_name: var2
  - var_name: var3
  - var_name: var4
  - var_name: var3
    output_name: var3_Z
    zbounds: 2. 3.
```

**Describe the solution you'd like**
It may be possible to take advantage of anchors to simplify this further.
```yaml
name: &name
  - var_name: var0
  - var_name: var1
  - var_name: var2
  - var_name: var3
  - var_name: var4
  - var_name: var3
    output_name: var3_Z
    zbounds: 2. 3.

title: test_none
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_4xdaily
  freq: 6 hours
  time_units: hours
  unlimdim: time
  module: ocn_mod
  reduction: none
  kind: r4
  varlist: *name
- file_name: test_daily
  freq: 1 days
  time_units: hours
  unlimdim: time
  module: ocn_mod
  reduction: none
  kind: r4
  varlist: *name
```

This will require expanding the yaml parser in FMS so that this can be supported.
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by thomas-robinson** [comment]
Will I be able to add more variables after the anchor?  For example:
```yaml
name: &name
  - var_name: var0
  - var_name: var1
  - var_name: var2
  - var_name: var3
  - var_name: var4
  - var_name: var3
    output_name: var3_Z
    zbounds: 2. 3.

title: test_none
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_4xdaily
  freq: 6 hours
  time_units: hours
  unlimdim: time
  module: ocn_mod
  reduction: none
  kind: r4
  varlist: *name
- file_name: test_daily
  freq: 1 days
  time_units: hours
  unlimdim: time
  module: ocn_mod
  reduction: none
  kind: r4
  varlist: *name
    - var_name: "new_var"
```

**Comment by uramirez8707** [comment]
> Will I be able to add more variables after the anchor? For example:

In that case, you will do
```
name: &name
  - var_name: var0
  - var_name: var1
  - var_name: var2
  - var_name: var3
  - var_name: var4
  - var_name: var3
    output_name: var3_Z
    zbounds: 2. 3.

title: test_none
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_4xdaily
  freq: 6 hours
  time_units: hours
  unlimdim: time
  module: ocn_mod
  reduction: none
  kind: r4
  varlist: *name
- file_name: test_daily
  freq: 1 days
  time_units: hours
  unlimdim: time
  module: ocn_mod
  reduction: none
  kind: r4
  varlist: 
    - *name
    - var_name: "new_var"
```
