### ISSUE TITLE
MODERN DIAG MANAGER: Potential to improve the diag_table yaml format further

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1678]
**Is your feature request related to a problem? Please describe.**
It is possible to specify the module at a file level and override it at a variable level, but there may be a case where say half of your variables are coming from one module and the other half form another. This will cause you duplicate the module name in multiple lines. For example, 

```yaml
title: test_none
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_4xdaily
  freq: 6 hours
  time_units: hours
  unlimdim: time
  module: radiation_mod
  reduction: none
  kind: r4
  varlist:
  - var_name: var0
  - var_name: var1
  - var_name: var2
  - var_name: var3
    module: some_other_mod
  - var_name: var4
    module: some_other_mod
  - var_name: var5
    module: some_other_mod
```

**Describe the solution you'd like**
It may be possible to simplify this further by doing:
```yaml
title: test_none
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_4xdaily
  freq: 6 hours
  time_units: hours
  unlimdim: time
  reduction: none
  kind: r4
  modules:
  - module: radiation_mod
    varlist:
    - var_name: var0
    - var_name: var1
    - var_name: var2
  - module: some_other_mod
    varlist:
    - var_name: var3
    - var_name: var4
    - var_name: var5
 ```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by uramirez8707** [comment]
> Will this allow the current format still?

Yes both formats will be allowed. However, you won't be able to combine the two for the same diag_file. For example, you can't do
```yaml
title: test_none
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_4xdaily
  freq: 6 hours
  time_units: hours
  unlimdim: time
  module: radiation_mod
  reduction: none
  kind: r4
  varlist:
  - var_name: var0
  - var_name: var1
  - var_name: var2
  - var_name: var3
  modules:
  - module: some_other_mod
    varlist:
    - var_name: var3
    - var_name: var4
    - var_name: var5
```
