### ISSUE TITLE
MODERN_DIAG_MANAGER: Bug when using new_file_freq and file_duration keys

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/FMS#1704]
**Describe the bug**
When using this diag_table yaml, the diag manager crashes with
```  FATAL from PE     0: diag_forecast_time_inc: illegal output units ```

```yaml
title: test_none
base_date: 2 1 1 0 0 0
diag_files:
- file_name: test_none%4yr%2mo%2dy%2hr
  freq: 6 hours
  time_units: hours
  unlimdim: time
  new_file_freq: 12 hours
  file_duration: 18 hours
  varlist:
  - module: ocn_mod
    var_name: var0
    output_name: var0_none
    reduction: none
    kind: r4
```

This yaml should have generated two files:
`test_none_0002_01_01_06.nc` with data from 0002-01-01 T 00 to 12
`test_none_0002_01_01_15.nc` with data from 0002-01-01 T 12 to 18

But it is crashing after 0002-01-01 T 18 because it attempting to finding the next time to write instead of  closing it.
It is also not setting the correct name of the second file, it should be `test_none_0002_01_01_15.nc` instead of `test_none_0002_01_01_18.nc`

**To Reproduce**
The unit test can reproduce this crash with the above diag_table.yaml.

and this input.nml
```
&diag_manager_nml 
 use_modern_diag=.true. 
 / 
```

`mpirun -n 6 ../test_reduction_methods `

**Expected behavior**
This case should work.

**System Environment**
This happens in any system

**Additional context**
N/A
